name: Render and Deploy Bookdown

on:
  push:
    branches:
      - master
      - main

jobs:
  build-bookdown:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      
      # Step 3: Set up Pandoc
      - name: Install
        uses: pandoc/actions/setup@v1

      # Step 4: Install renv and restore dependencies integrated with github cache
      - uses: r-lib/actions/setup-renv@v2

      # Step 5: Render Bookdown
      - name: Render Bookdown
        run: |
          R -e 'bookdown::render_book("index.Rmd")'

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.BOOK_TOKEN }}
          publish_dir: ./_book
